TheGameHistorico/TheGameHistorico/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from django.urls.base import reverse_lazy
from django.urls.conf import include
from django.views.generic.base import RedirectView
from django.views.generic.edit import UpdateView

import games
import users

from . import views


urlpatterns = [
    path('', views.homeSec, name='sec-home'),
    path('admin/', admin.site.urls),
    path("users/", include ('users.urls')),
    path('games/', include('games.urls')),
    path('games/listaPublica/', games.views.GamePublicListView.as_view(), name='lista-publica-games'),
    path('games/adicionarJogo/', games.views.GameCreateView.as_view(), name='registrar-novo-jogo'),
    path('games/atualizarJogo/<int:pk>/', games.views.GameUpdateView.as_view(), name='atualizar-jogo'),
    path('games/apagarJogo/<int:pk>/', games.views.GameDeleteView.as_view(), name='remover-jogo'),
    path('games/listar/', games.views.GameListView.as_view(), name='lista-games'), 
    path('templates/', views.homeSec, name='nav-bar-home'),
    path('accounts/users/', users.views.RegisterNewUserView.as_view(), name = 'sec-registro'),
    path('sobreoSite/', views.sobre, name='sobre-o-site'),
    path('exibeCharsRest/', users.views.exibeCharsRestantes, name='exibeCharsRest'),
    path('verificaUsername/', users.views.verificaUsername, name='verificaUsername'),
    path('accounts/login/', LoginView.as_view(template_name='users/login.html'), name='sec-login',), # was LoginView.as_view(template_name='users/login.html', )
    # path('accounts/profile/', users.views.paginaProfile, name='sec-paginaProfile', ),
    path('accounts/profile/', users.views.paginaProfile, name='sec-paginaProfile'),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('sec-home')), name="sec-logout"),
    path('accounts/trocaSenha/', PasswordChangeView.as_view(template_name='users/password_change_form.html', success_url = reverse_lazy('sec-passwordDone')), name='sec-passwordChange'),
    path('accounts/senhaTrocada/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html', ), name='sec-passwordDone'),
    path('favicon.ico', RedirectView.as_view(url='static/favicon.ico')),
    path('accounts/password_reset/', PasswordResetView.as_view( 
           template_name='users/password_reset_form.html',  
           success_url=reverse_lazy('sec-password_reset_done'), 
           email_template_name='users/password_reset_email.html', 
           subject_template_name='users/password_reset_subject.txt', 
           from_email='felipe@philisoftstudio.com', 
         ), name='password_reset'), 
     
    path('accounts/password_reset_done/', PasswordResetDoneView.as_view( 
           template_name='users/password_reset_done.html', 
         ), name='sec-password_reset_done'), 
     
    path('accounts/password_reset_confirm/<uidb64>/<token>/',  
         PasswordResetConfirmView.as_view( 
           template_name='users/password_reset_confirm.html',  
           success_url=reverse_lazy('sec-password_reset_complete'), 
         ), name='password_reset_confirm'), 
     
    path('accounts/password_reset_complete/', PasswordResetCompleteView.as_view( 
           template_name='users/password_reset_complete.html' 
         ), name='sec-password_reset_complete'),
    
    path('accounts/terminaRegistro/<int:pk>/', users.views.UserUpdateView.as_view(), name='sec-completaDadosUsuario'),
    # path('accounts/profile/', users.views.showUserBio, name='sec-userBio')
]

games/urls.py
'''
Created on Nov 20, 2021

@author: felipe
''' 
from django.urls.conf import path

from games import views


app_name='games'

urlpatterns = [
    # path('games/atualizaGame')
    ]
#
#     # path('', views.ContatoListView.as_view(),  
#     #     name='home-jogos'), 

thegamehistorico/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from django.urls.base import reverse_lazy
from django.urls.conf import include
from django.views.generic.base import RedirectView
from django.views.generic.edit import UpdateView

import games
import users
from . import views


urlpatterns = [
    path('', views.homeSec, name='sec-home'),
    path('admin/', admin.site.urls),
    path("users/", include ('users.urls')),
    path('games/', include('games.urls')),
    path('games/listaPublica/', games.views.GamePublicListView.as_view(), name='lista-publica-games'),
    path('games/adicionarJogo/', games.views.GameCreateView.as_view(), name='registrar-novo-jogo'),
    path('games/atualizarJogo/<int:pk>/', games.views.GameUpdateView.as_view(), name='atualizar-jogo'),
    path('games/apagarJogo/<int:pk>/', games.views.GameDeleteView.as_view(), name='remover-jogo'),
    path('games/listar/', games.views.GameListView.as_view(), name='lista-games'), 
    path('templates/', views.homeSec, name='nav-bar-home'),
    path('accounts/users/', users.views.RegisterNewUserView.as_view(), name = 'sec-registro'),
    path('sobreoSite/', views.sobre, name='sobre-o-site'),
    path('exibeCharsRest/', users.views.exibeCharsRestantes, name='exibeCharsRest'),
    path('verificaUsername/', users.views.verificaUsername, name='verificaUsername'),
    path('accounts/login/', LoginView.as_view(template_name='users/login.html'), name='sec-login',), # was LoginView.as_view(template_name='users/login.html', )
    # path('accounts/profile/', users.views.paginaProfile, name='sec-paginaProfile', ),
    path('accounts/profile/', users.views.paginaProfile, name='sec-paginaProfile'),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('sec-home')), name="sec-logout"),
    path('accounts/trocaSenha/', PasswordChangeView.as_view(template_name='users/password_change_form.html', success_url = reverse_lazy('sec-passwordDone')), name='sec-passwordChange'),
    path('accounts/senhaTrocada/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html', ), name='sec-passwordDone'),
    path('favicon.ico', RedirectView.as_view(url='static/favicon.ico')),
    path('accounts/password_reset/', PasswordResetView.as_view( 
           template_name='users/password_reset_form.html',  
           success_url=reverse_lazy('sec-password_reset_done'), 
           email_template_name='users/password_reset_email.html', 
           subject_template_name='users/password_reset_subject.txt', 
           from_email='felipe@philisoftstudio.com', 
         ), name='password_reset'), 
     
    path('accounts/password_reset_done/', PasswordResetDoneView.as_view( 
           template_name='users/password_reset_done.html', 
         ), name='sec-password_reset_done'), 
     
    path('accounts/password_reset_confirm/<uidb64>/<token>/',  
         PasswordResetConfirmView.as_view( 
           template_name='users/password_reset_confirm.html',  
           success_url=reverse_lazy('sec-password_reset_complete'), 
         ), name='password_reset_confirm'), 
     
    path('accounts/password_reset_complete/', PasswordResetCompleteView.as_view( 
           template_name='users/password_reset_complete.html' 
         ), name='sec-password_reset_complete'),
    
    path('accounts/terminaRegistro/<int:pk>/', users.views.UserUpdateView.as_view(), name='sec-completaDadosUsuario'),
    # path('accounts/profile/', users.views.showUserBio, name='sec-userBio')
]

games/models.py
from _datetime import date

from django.db import models
import django.utils.timezone

from users.models import User 


# Create your models here.
class Game(models.Model):
    BOOL_VALS =((0,'False'), (1, 'True'),)
    id=models.AutoField(primary_key=True, unique=True, default=None)
    owner = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name="usuario_username", editable=False)
    # user_username = models.ForeignKey(users.models.Usuario, default=1, verbose_name="Usuario", on_delete=models.SET_DEFAULT)
    title= models.CharField(max_length=512)
    developer=models.CharField(max_length=512)
    publisher=models.CharField(max_length=512)
    # playing=models.IntegerField(choices=BOOL_VALS)
    # mainquest=models.IntegerField(choices=BOOL_VALS)
    # mainquestPlus=models.IntegerField(choices=BOOL_VALS)
    # complete=models.IntegerField(choices=BOOL_VALS)
    time_playing=models.TimeField(default='00:00:00', null=True, blank=True)
    CHOICES = (
        ('opt1','Ainda jogando'),
        ('opt2','Apenas Quest Principal'),
        ('opt3','Principal + alguns Extras'), 
        ('opt4','Complecionista'),
        )

    
    status=models.CharField(max_length=100, choices = CHOICES, default='opt1', null=True, blank=True)
    
    time_completion = models.DateField(default= django.utils.timezone.now, null=True, blank=True)
    
    cover_path=models.CharField(max_length=254, null=True, blank=True)
    PLATS = (
        ('opt0', 'Unlisted'),
        ( 'opt1', 'Switch' ),
        ('opt2', 'Wii U'),
        ('opt3', 'Wii'),
        ('opt4', 'GameCube'),
        ('opt5', 'N64'),
        ('opt6', 'SNES'),
        ('opt7', 'NES'),
        ('opt8' , 'GBA'),
        ('opt9', 'GBC'),
        ('opt10', 'GB'),
        ( 'opt11', 'PS1' ),
        ( 'opt12', 'PS2' ),
        ( 'opt13', 'PS3' ),
        ( 'opt14', 'PS4' ),
        ( 'opt15', 'PS5' ),
        ( 'opt16', 'Xbox' ),
        ( 'opt17', 'Xbox 360' ),
        ('opt18' , 'Xbox One'),
        ('opt19' , 'Xbox Series'),
        ('opt20', 'PSP'),
        ('opt21', 'PSVita'),
        ('opt22', 'NDS' ),
        ('opt23', '3DS'),
        ('opt24', 'New3DS'),
        ('opt25', 'Atari 2600'),
        ('opt26', 'Apple ]['),
        ('opt27' , 'PC'),
        )
    platform = models.CharField(max_length=15, choices = PLATS, default ='opt0', null=True, blank=True)
    # def __str__(self):
    #     return self.title

games/views.py
import io
import re
import ssl
import urllib

from django.conf import settings
from django.contrib import sessions
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import exceptions
from django.http.response import HttpResponse, HttpResponseRedirect
from django.http.response import HttpResponseRedirect 
from django.shortcuts import render, get_object_or_404, _get_queryset 
from django.urls.base import reverse_lazy
from django.views.generic.base import View 

from PIL import Image
from games.forms import NewGameForm
from games.models import Game
import users


# Create your views here.
# def registraJogo(request):
#     # return HttpResponse("ola")
#     if request.method == "POST":
#         formulario = NewGameForm(request.POST)
#         if formulario.is_valid():
#             formulario.save()
#             titulo = formulario.Titulo_do_jogo
#             # list = get_cover(titulo)
#             return HttpResponse(str(list)) #redirect('sec-home')
#     else:
#         formulario = NewGameForm()
#
#
#     contexto = {'formularioGame' : formulario, }
#     return render(request, "games/registroGame.html", contexto)
class GameListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs): 
        game = Game.objects.filter(usuario_id=request.user.id)
        
        context = {'game': game, } 
        return render(request, 'users/paginaProfile.html', context)

@login_required
def listGames(request):
    games = Game.objects.filter(owner_id=request.user.pk).all()
    return games


def cover_crawler(title):
    ssl._create_default_https_context = ssl._create_unverified_context
    query1 = title
    query2 = query1.replace(" ", "%20")
    output = ''
    str1 = '<img src="https://vgcollect.com/images/front-box-art/'
    lenMax = len(str1)

    with urllib.request.urlopen("https://vgcollect.com/search/" + query2) as response:
        html = str(response.read())
        # seq = re.findall('\"span2 item-art\"', str(html))
        # print(seq)
        #    for i in range(len(str(html))):
        # f.write(str(seq))
        j = html.find("[NA]")
        # j = html.find("\"span2 item-art\"")
        # print(j)
        k = j - 2
        for i in range(k, len(html) - lenMax):
            # print(i)
            if html.find(str1, i, i + lenMax) > 0:

                temp = html[i : i + lenMax + 20]
                urltest = temp[10 : temp.find(".jpg") + 4]
               
                # print(urltest)

                picname = urllib.request.urlopen(urltest)
                file = io.BytesIO(picname.read())
                im = Image.open(file)
                output = 'games/static/games/img/'+ query1 + '.jpg'
                im.save(output)
                break
    return '/static/games/img/'+ query1 + '.jpg'

        
class GameCreateView(LoginRequiredMixin, View): 
    def get(self, request, *args, **kwargs): 
        # print(request.user.username)
        # try:
        #     print(request.user)
        # except:
        #     print('não achei')
        context = { 'formularioGame': NewGameForm, } 
        
        return render(request, "games/registroGame.html", context) 
     
    def post(self, request, *args, **kwargs): 
        formulario = NewGameForm(request.POST)
        
        # print(formulario)
        if formulario.is_valid(): 
            game = formulario.save(commit=False)
            game.owner = users.views.User.objects.get(username=request.user.username)
            # game.usuario_id = request.user
            # game.usuario_id = Usuario.objects.get(usuario_id=request.user.pk)
            # print(str(game.owner))
            game.cover_path = cover_crawler(game.title)
            game.save() 
        else:
            context = { 'formularioGame': NewGameForm, } 
            return render(request, "games/registroGame.html", context)
            # Game.objects.create(game)
            # return HttpResponseRedirect(reverse_lazy("sec-paginaProfile"))
        # else:
        
        return HttpResponseRedirect(reverse_lazy("sec-paginaProfile")) 
            # formulario = NewGameForm()
        
        # contexto = {'formularioGame' : formulario, }
        # return render(request, "users/paginaProfile.html", contexto)

        
 
class GameUpdateView(LoginRequiredMixin, View): 
    def get(self, request, pk, *args, **kwargs): 
        game = Game.objects.get(pk=pk) 
        formulario = NewGameForm(instance=game) 
        context = {'game': formulario, } 
        return render(request, 'games/atualizaGame.html', context) 
     
    def post(self, request, pk, *args, **kwargs): 
        if request.POST.get("ok"):
            pessoa = get_object_or_404(Game, pk=pk) 
            formulario = NewGameForm(request.POST, instance=pessoa) 
            if formulario.is_valid(): 
                pessoa = formulario.save() 
                pessoa.cover_path = cover_crawler(pessoa.title) 
                pessoa.save()
                return HttpResponseRedirect(reverse_lazy("sec-paginaProfile")) 
            else: 
                context = {'game': formulario, } 
                return render(request, 'games/atualizaGame.html', context)
        else:
            pass
        return HttpResponseRedirect(reverse_lazy("sec-paginaProfile"))
        
class GameDeleteView(LoginRequiredMixin, View): 
    def get(self, request, pk, *args, **kwargs): 
        game = Game.objects.get(pk=pk) 
        context = {'game': game, } 
        return render(request, 'games/apagaGame.html', context)
    
    def post(self, request, pk, *args, **kwargs):
        if request.POST.get("remove-btn"):
            game = Game.objects.get(pk=pk)
            game.delete() 
            print("Removendo o jogo", pk) 
            
        return HttpResponseRedirect(reverse_lazy("sec-paginaProfile")) 
    
    
# def getGamePublicList():
#     return games

class GamePublicListView(View):
    def get(self, request, *args, **kwargs): 
        gameList = []
        games = Game.objects.all()

        for e in Game.objects.all():
            if request.GET.get("gameTitle") in e.title:
                gameList.append(e)

        if len(gameList) > 0:
            context = { 'game' : gameList }
        else:
            context = { 'game' : games }
                   
        return render(request, 'games/grid.html', context)             
        # return render(request, 'games/grid.html', context)
        
        

games/templates/games/apagaGame.html
{% extends 'games/base.html' %}
{% load static %}
{% block content %}
    <h2>Remoção de Game da Lista</h2>
    </br></br>
    <h3>Confirma a remoção de {{ game.title }}?</h3>
    </br></br></br> 
    <form method="POST">
         {% csrf_token %} 
         <input class="btn btn-secondary" name="cancela-btn" type="submit" value="Cancelar">
        <input class="btn btn-primary" name="remove-btn" type="submit" value="Remover"> 
    </form>
{% endblock %}

games/templates/games/atualizaGame.html
{% extends 'games/base.html' %} 
{% load static %}
{% block conteudo %} 
<div class="container bg-dark text-white col-xl-5 col-lg-8 col-md-10 col-sm-10 col-10">       
	 <div class="center m-4">
	  <h1>Atualização dos jogos</h1> 
	  <form method="POST" class="form-control bg-dark text-light"> 
	    {% csrf_token %} 
	    <table> 
	      {{ game.as_table }} 
	        <tr> 
	          <td></td> 
	          <td><input class="mb-2 mt-2 btn btn-primary" type="submit" name="ok" value="Atualizar">
	        <input class="btn btn-secondary" name="cancela-btn" type="submit" value="Cancelar"></td> 
	        </tr> 
	    </table>
	  </form> 
	</div>
</div>    
{% endblock %}

games/templates/games/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width">
        <meta title="{% block titulo %}{% endblock %}">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'games/css/styles.css' %}" rel="stylesheet" />
       	<!-- jQuery -->
        <script type="text/javascript" src="{% static 'games/js/script.js' %}"></script>
       
    </head>
    <body>
        {% include 'header.html' %}
        {% block content %}
        <header class="call-to-action">
            <section class="position-relative features-icons text-align-left">           
            {% block conteudo %}{% endblock %}
            </section>
        </header>
        {% endblock %}
         {% include 'footer.html' %}
    </body>
</html>

games/templates/games/grid.html
{% extends 'games/base.html' %}
{% load static %}
{% block conteudo %}
		<section class="bg-dark text-center col-md-12 col-12 col-xs-12 col-sm-12 col-xl-12">
		<h4 class="text-light pt-5">Games já adicionados à plataforma</h4>
            <div class="container pt-5 pb-5">
             <div class="row text-light">
            {% if game %}
	  		{% for g in game %}
                    <div class="col-lg-4">
                            <div class="features-icons-icon"><img src="{{ g.cover_path }}"></div>
                            <h4 class="m-2">{{ g.title }}</h4>
                            <p class="lead mb-0">{{ g.developer }}</p>
                            <p class="lead mb-0">{{ g.publisher }}</p>
                            <p class="lead mb-0">{{ g.get_platform_display }}</p>
                    </div>
   	  		{% endfor %}
	  		{% endif %}
                    
                </div>
            </div>
        </section>       
{% endblock %} 

games/templates/games/listaGames.html
<!DOCTYPE html> 
{% load static %} 
<html> 
<head> 
<meta charset="UTF-8"> 
<link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
</head> 
<body> 
    <h3>Sua Lista Pessoal de Jogos</h3> 
    <table class="table text-light"> 
        <tr><th>Título</th><th>Tempo de Jogo</th><th>Status</th><th>Plataforma</th><th>Conclusão</th><th>Ações</th></tr> 
        {% if games %}
        {% for g in games %} 
            <tr> 
                <td>{{ g.title }}</td><td>{{g.time_playing}}</td><td>{{ g.get_status_display }}</td><td>{{ g.get_platform_display }}</td>
                <td>{% if g.status != "opt1" %}{{ g.time_completion }}{% else %}{{ g.get_status_display }}{% endif %}</td>
                <td><a href="{% url 'atualizar-jogo' pk=g.id %}">Atualizar</a>
                	<a href="{% url 'remover-jogo' pk=g.id %}">Remover</a>
                </td> 
           </tr> 
        {% endfor %}
        {% else %}
            <tr><th colspan="5">Ainda não há jogos registrados</th></tr> 
        {% endif %} 
    </table> 
</body> 
</html>

games/templates/games/registroGame.html
{% extends 'games/base.html' %}
{% load static %}
<html>
<head>
</head>
<body>
<!-- Titulo da página -->
{% block titulo %}Incluir novo jogo{% endblock %}
<!-- Conteúdo da página -->
{% block conteudo %}
<div class="container bg-dark text-white col-xl-5 col-lg-8 col-md-10 col-sm-10 col-10">       
   <div class="center m-0">
		<h2 class="text-center text-light p-5">Registrar um novo jogo</h2>
		<form method="POST" class="form-control bg-dark text-light">
		    {% csrf_token %}
		    <table>
		        {{ formularioGame.as_table }}
		    </table>
		    <input class="mb-4 ms-4 mt-4 btn btn-primary" type="submit" value="Confirmar registro">
		</form>
	</div>
</div>
{% endblock %}
</body>
</html>